# Generated by Django 6.0.4 on 2026-05-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
